In [3]:
pip install numpy

   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
    --------------------------------------- 0.3/12.6 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.6 MB 758.3 kB/s eta 0:00:16
   - -------------------------------------- 0.5/12.6 MB 758.3 kB/s eta 0:00:16
   -- ------------------------------------- 0.8/12.6 MB 667.1 kB/s eta 0:00:18
   -- ------------------------------------- 0.8/12.6 MB 667.1 kB/s eta 0:00:18
   --- ------------------------------------ 1.0/12.6 MB 599.9 kB/s eta 0:00:20
   --- ------------------------------------ 1

In [1]:
import numpy as np
print("numpy version:",np.__version__)

numpy version: 2.5.1


In [2]:
# AI & ML Internship - Day 3
# Topic : NumPy Fundamentals
# Description : Working with NumPy arrays and mathematical operations
import numpy as np

print("=" * 60)
print("          NUMPY FUNDAMENTALS DEMONSTRATION")
print("=" * 60)

# Create a NumPy array
student_marks = np.array([78, 85, 92, 67, 88])

print("\nOriginal Array:")
print(student_marks)

# Array Information
print("\nArray Information")
print("Dimensions :", student_marks.ndim)
print("Shape      :", student_marks.shape)
print("Data Type  :", student_marks.dtype)
print("Size       :", student_marks.size)

# Indexing
print("\nIndexing")
print("First Element :", student_marks[0])
print("Last Element  :", student_marks[-1])

# Slicing
print("\nSlicing")
print("First Three Elements :", student_marks[:3])
print("Last Two Elements    :", student_marks[-2:])

# Mathematical Operations
print("\nMathematical Operations")
print("Add 5      :", student_marks + 5)
print("Multiply 2 :", student_marks * 2)
print("Square     :", np.square(student_marks))

# Statistical Operations
print("\nStatistical Analysis")
print("Sum     :", np.sum(student_marks))
print("Average :", np.mean(student_marks))
print("Maximum :", np.max(student_marks))
print("Minimum :", np.min(student_marks))
print("Median  :", np.median(student_marks))
print("Standard Deviation :", np.std(student_marks))

# 2D Array
matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

print("\n2D Array")
print(matrix)

print("\nElement at Row 2, Column 3 :", matrix[1, 2])

print("\nRow-wise Sum :", np.sum(matrix, axis=1))
print("Column-wise Sum :", np.sum(matrix, axis=0))

print("\n" + "=" * 60)
print("NumPy Fundamentals Completed Successfully")
print("=" * 60)

          NUMPY FUNDAMENTALS DEMONSTRATION

Original Array:
[78 85 92 67 88]

Array Information
Dimensions : 1
Shape      : (5,)
Data Type  : int64
Size       : 5

Indexing
First Element : 78
Last Element  : 88

Slicing
First Three Elements : [78 85 92]
Last Two Elements    : [67 88]

Mathematical Operations
Add 5      : [83 90 97 72 93]
Multiply 2 : [156 170 184 134 176]
Square     : [6084 7225 8464 4489 7744]

Statistical Analysis
Sum     : 410
Average : 82.0
Maximum : 92
Minimum : 67
Median  : 85.0
Standard Deviation : 8.78635305459552

2D Array
[[10 20 30]
 [40 50 60]]

Element at Row 2, Column 3 : 60

Row-wise Sum : [ 60 150]
Column-wise Sum : [50 70 90]

NumPy Fundamentals Completed Successfully
